version: "3.3"

services: 
  s1_wb:
    image: asatrya/vuejs:2-webpack
    container_name: vuejs_webpack
    ports:
      - "8081:8080"
    volumes:
      - ${PWD}/src:/app/src
    stdin_open: true
    tty: true
    # environment:
    #   - NODE_ENV=development
    #   - CHOKIDAR_USEPOLLING=true
    #   - CHOKIDAR_INTERVAL=100
    #   - YOUR_APP_WEB_HTTP_PORT=8080